;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	easy-kill
	easy-kill-abort
	easy-kill-append
	easy-kill-delete-region
	easy-kill-digit-argument
	easy-kill-expand
	easy-kill-mark-region
	easy-kill-region
	easy-kill-shrink
	easy-kill-thing
	easy-kill-unhighlight
	easy-mark
	))

(setq mc/cmds-to-run-once
      '(
	easy-kill-help
	iedit-switch-to-mc-mode
	smart-region
	))
