(("default" . ((user-emacs-directory . "~/emacs/.default")))
 ("centaur" . ((user-emacs-directory . "~/emacs/centaur")))
 ("doom" . ((user-emacs-directory . "~/emacs/doom")
            (env . (("DOOMDIR" . "~/emacs/doom/doom.d")))))
 (".doom.backup" . ((user-emacs-directory . "~/emacs/.doom.backup")
            (env . (("DOOMDIR" . "~/emacs/.doom.backup/doom.d")))))
 )
